# Generated by Django 5.1.6 on 2025-07-13 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recordings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recording',
            options={'ordering': ['created_at'], 'verbose_name': 'Recordings', 'verbose_name_plural': 'Recordings'},
        ),
    ]
