# Generated by Django 5.1.6 on 2025-06-23 17:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicCounsellor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.SlugField(default=uuid.uuid4, unique=True)),
                ('active_status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('employee_id', models.CharField(max_length=10)),
                ('photo', models.ImageField(upload_to='academic-counsellors')),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.CharField(max_length=12)),
                ('house_name', models.CharField(max_length=25)),
                ('post_office', models.CharField(max_length=25)),
                ('district', models.CharField(choices=[('Thiruvananthapuram', 'Thiruvananthapuram'), ('Kollam', 'Kollam'), ('Pathanamthitta', 'Pathanamthitta'), ('Alappuzha', 'Alappuzha'), ('Kottayam', 'Kottayam'), ('Idukki', 'Idukki'), ('Ernakulam', 'Ernakulam'), ('Thrissur', 'Thrissur'), ('Palakkad', 'Palakkad'), ('Malappuram', 'Malappuram'), ('Kozhikkod', 'Kozhikkod'), ('Vayanadu', 'Vayanadu'), ('Kannur', 'Kannur'), ('Kazargod', 'Kazargod')], max_length=20)),
                ('pincode', models.CharField(max_length=6)),
                ('qualification', models.CharField(choices=[('UG', 'UG'), ('PG', 'PG'), ('Diploma', 'Diploma')], max_length=10)),
                ('stream', models.CharField(max_length=25)),
                ('id_proof', models.FileField(upload_to='academic-counsellors/idproof')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Academic Counsellor',
                'verbose_name_plural': 'Academic Counsellor',
            },
        ),
    ]
