# Generated by Django 5.1.6 on 2025-06-24 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_counsellors', '0001_initial'),
        ('batches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='batches',
            name='academic_counsellor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='academic_counsellors.academiccounsellor'),
        ),
    ]
