# Generated by Django 5.1.6 on 2025-07-14 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batches', '0002_batches_academic_counsellor'),
        ('trainers', '0002_trainers_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='batches',
            name='trainer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='trainers.trainers'),
        ),
    ]
