# Generated by Django 5.1.6 on 2025-07-14 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batches', '0003_batches_trainer'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='batches',
            name='courses',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.courses'),
        ),
    ]
